"""FastAPI routes for the cert-reporter API."""

from __future__ import annotations

import io
import os
from pathlib import Path

from fastapi import APIRouter, HTTPException, Query, Request
from fastapi.responses import FileResponse, StreamingResponse

# Workspace root lives at certifier/workspace/.
# If WORKSPACE_DIR is a relative path (e.g. "workspace"), resolve it from
# _CERTIFIER_ROOT so it never ends up inside cert_reporter/.
_CERTIFIER_ROOT = Path(__file__).resolve().parent.parent.parent   # cert_reporter/api/ → certifier/
_ws_env = os.getenv("WORKSPACE_DIR")
_WORKSPACE_DIR: Path = (
    Path(_ws_env) if (_ws_env and Path(_ws_env).is_absolute())
    else _CERTIFIER_ROOT / (_ws_env or "workspace")
)

router = APIRouter()


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _find_latest(agent_id: str, experiment_id: str, ext: str) -> Path | None:
    """Return the most recently modified .html or .pdf in the certification dir."""
    cert_dir = _WORKSPACE_DIR / agent_id / experiment_id / "certification"
    if not cert_dir.is_dir():
        return None
    files = sorted(cert_dir.glob(f"*.{ext}"), key=lambda p: p.stat().st_mtime, reverse=True)
    return files[0] if files else None


async def _gridfs_stream(gridfs_bucket, agent_id: str, experiment_id: str, fmt: str):
    """Return a StreamingResponse from GridFS for the most recent matching file, or None."""
    cursor = gridfs_bucket.find(
        {"metadata.agent_id": agent_id, "metadata.experiment_id": experiment_id,
         "metadata.format": fmt},
        sort=[("uploadDate", -1)],
        limit=1,
    )
    grid_out = None
    async for doc in cursor:
        grid_out = doc
        break
    if grid_out is None:
        return None
    content_type = "application/pdf" if fmt == "pdf" else "text/html"
    data = await grid_out.read()
    return StreamingResponse(
        io.BytesIO(data),
        media_type=content_type,
        headers={"Content-Disposition": f'attachment; filename="{grid_out.filename}"'},
    )


# ---------------------------------------------------------------------------
# Endpoints
# ---------------------------------------------------------------------------

@router.get("/certification/pdf")
async def get_certification_pdf(
    request: Request,
    agent_id: str = Query(..., description="Agent ID used in POST /api/v1/aggregation-certification"),
    experiment_id: str = Query(..., description="Experiment ID used in POST /api/v1/aggregation-certification"),
):
    """
    Return the PDF certification report for the given agent/experiment.

    Tries GridFS first (when MongoDB is configured), then falls back to the
    filesystem workspace.  The report must already have been generated by
    ``POST /api/v1/aggregation-certification``.
    """
    gridfs_bucket = getattr(request.app.state, "gridfs_bucket", None)
    if gridfs_bucket is not None:
        response = await _gridfs_stream(gridfs_bucket, agent_id, experiment_id, "pdf")
        if response is not None:
            return response

    file_path = _find_latest(agent_id, experiment_id, "pdf")
    if not file_path:
        raise HTTPException(status_code=404, detail="No PDF found")
    return FileResponse(
        path=str(file_path),
        media_type="application/pdf",
        filename=file_path.name,
    )


@router.get("/certification/html")
async def get_certification_html(
    request: Request,
    agent_id: str = Query(..., description="Agent ID used in POST /api/v1/aggregation-certification"),
    experiment_id: str = Query(..., description="Experiment ID used in POST /api/v1/aggregation-certification"),
):
    """
    Return the HTML certification report for the given agent/experiment.

    Tries GridFS first (when MongoDB is configured), then falls back to the
    filesystem workspace.  The report must already have been generated by
    ``POST /api/v1/aggregation-certification``.
    """
    gridfs_bucket = getattr(request.app.state, "gridfs_bucket", None)
    if gridfs_bucket is not None:
        response = await _gridfs_stream(gridfs_bucket, agent_id, experiment_id, "html")
        if response is not None:
            return response

    file_path = _find_latest(agent_id, experiment_id, "html")
    if not file_path:
        raise HTTPException(status_code=404, detail="No HTML found")
    return FileResponse(
        path=str(file_path),
        media_type="text/html",
        filename=file_path.name,
    )
