"""FastAPI routes for the cert-reporter API."""

from __future__ import annotations

import os
from pathlib import Path

from fastapi import APIRouter, HTTPException
from fastapi.responses import FileResponse

from .models import GenerateRequest

# Workspace root lives at certifier/workspace/.
# If WORKSPACE_DIR is a relative path (e.g. "workspace"), resolve it from
# _CERTIFIER_ROOT so it never ends up inside cert_reporter/.
_CERTIFIER_ROOT = Path(__file__).resolve().parent.parent.parent   # cert_reporter/api/ → certifier/
_ws_env = os.getenv("WORKSPACE_DIR")
_WORKSPACE_DIR: Path = (
    Path(_ws_env) if (_ws_env and Path(_ws_env).is_absolute())
    else _CERTIFIER_ROOT / (_ws_env or "workspace")
)

router = APIRouter()


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _find_latest(agent_id: str, experiment_id: str, ext: str) -> Path | None:
    """Return the most recently modified .html or .pdf in the certification dir."""
    cert_dir = _WORKSPACE_DIR / agent_id / experiment_id / "certification"
    if not cert_dir.is_dir():
        return None
    files = sorted(cert_dir.glob(f"*.{ext}"), key=lambda p: p.stat().st_mtime, reverse=True)
    return files[0] if files else None


# ---------------------------------------------------------------------------
# Endpoints
# ---------------------------------------------------------------------------

@router.post("/generate/pdf")
def generate_pdf(req: GenerateRequest):
    """
    Return the PDF certification report for the given agent/experiment.

    The report must already have been generated by POST /api/v1/aggregation-certification.
    Reads: ``workspace/{agent_id}/{experiment_id}/certification/*.pdf``
    """
    file_path = _find_latest(req.agent_id, req.experiment_id, "pdf")
    if not file_path:
        raise HTTPException(
            status_code=404,
            detail=(
                f"No PDF report found for agent_id='{req.agent_id}', "
                f"experiment_id='{req.experiment_id}'. "
                "Run POST /api/v1/aggregation-certification first."
            ),
        )
    return FileResponse(
        path=str(file_path),
        media_type="application/pdf",
        filename=file_path.name,
    )


@router.post("/generate/html")
def generate_html(req: GenerateRequest):
    """
    Return the HTML certification report for the given agent/experiment.

    The report must already have been generated by POST /api/v1/aggregation-certification.
    Reads: ``workspace/{agent_id}/{experiment_id}/certification/*.html``
    """
    file_path = _find_latest(req.agent_id, req.experiment_id, "html")
    if not file_path:
        raise HTTPException(
            status_code=404,
            detail=(
                f"No HTML report found for agent_id='{req.agent_id}', "
                f"experiment_id='{req.experiment_id}'. "
                "Run POST /api/v1/aggregation-certification first."
            ),
        )
    return FileResponse(
        path=str(file_path),
        media_type="text/html",
        filename=file_path.name,
    )
